name: Checkout
on: [push]
jobs:
  code-checkout:
    runs-on: ubuntu-latest
    steps:
      - name: check before checkout
        run: |
          pwd
          ls -a
      - name: checkout
        uses: actions/checkout@v1 
      - name: check after checkout
        run: |
          pwd
          ls -a
      - name: Environment Variables
        run: |
          echo $GITHUB_SHA
          echo $GITHUB_REPOSITORY
          echo $GITHUB_REPOSITORY_OWNER
          echo $GITHUB_WORKSPACE
          echo $RUNNER_NAME
          echo "${{ github.token }}"