name: compledx
on: push
jobs:
  ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: ubuntu
        run: date
  window:
    runs-on: windows-latest
    steps:
      - name: ubuntu
        run: date
  macos:
    runs-on: macos-latest
    steps:
      - name: ubuntu
        run: date
  depends:
    needs: [ubuntu,windows,macos]
    runs-on: macos-latest
    steps:
      - name: ubuntu
        run: date