name: push random file
on: [push]
jobs:
  code-checkout:
    runs-on: ubuntu-latest
    steps:
      - name: push random file
        run: |
          pwd
          ls -a
          git init
          git remote add origin "https://$GITHUB_ACTOR:${{secrets.GITHUB_TOKEN}}@github.com/$GITHUB_REPOSITORY.git"
          git config --global user.email "bot@bot.com"
          git config --global user.name "bot"
          git fetch
          git checkout main
          git branch --set-upstream-to=origin/main
          git pull
          ls -a
          echo $RANDOM >> random.txt
          ls -a
          git add .
          git commit -m "creating file"
          git push