name: cron job
on:
#  push
    # branches:
    #   - "master"
    #   - "develop"
    # branches-ignore:
    #   - "devops"
    # tags:
    #   - v1.*
    # tags-ignore:
    #   - 
    # paths:
    #   - "path of the file"
    # paths-ignore:
    #   - "ignore path"
    
  repository_dispatch:
    types: [build]

jobs:
  cron-job:
    runs-on: ubuntu-latest
    steps:
      - name: cron job
        run: echo "Cron Job! && repository dispatch"
      - name: payload event
        run: echo ${{ github.event.client_payload.env }}