name: cron job
on: 
  repository_dispatch:
    types: [build]

jobs:
  cron-job:
    runs-on: ubuntu-latest
    steps:
      - name: cron job
        run: echo "Cron Job! && repository dispatch"
      - name: payload event
        run: echo ${{ github.event.client_payload.env }}