name: Matrix testing
on: push

jobs:
  node-version:
    strategy:
      matrix:
        os_version: [macos-latest, ubunt-latest, windows-latest]
        node_version: [6, 8, 10]
      fail-fast: true
    runs-on: ${{ matrix.os_version }}
    steps:
      - name: Log Node Version
        run: node -v
      - name: another node version
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node_version }}
      - name: Log Node Version
        run: node -v