name: Context testing
on: push

jobs:
  node-version:
    step:
      - name: Log Node Version
        run: node -v
      - name: another node version
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - name: Log Node Version
        run: node -v