name: Secrets
on: [pull_request]
env:
  my_name: ${{secrets.my_name}}
jobs:
  serets:
    runs-on: ubuntu-latest
    steps:
      - name: secrets
        run: |
          echo "My name is: ${my_name}"
  