name: Shell commands
on: [push]
jobs:
  hello-world:
    runs-on: ubuntu-latest
    steps:
      - name: Hello World
        run: echo "Hello World!"
  get-versions:
    runs-on: ubuntu-latest
    steps:
      - name: npm versions
        run: | 
          node --version
          npm --version
      - name: ansible version
        run: ansible --version
      - name: other version
        run: |
          packer --version
          python --version
          java --version
          dotnet --version
          nginx -V
  python-script:
    runs-on: ubuntu-latest
    steps:
      - name: Python Script
        run: |
          import platform
          print(platform.processor())
          print(platform.architecture())
        shell: python
  windows-script:
    runs-on: windows-latest
    needs: [hello-world]
    steps:
      - name: default powershell
        run: Get-Location
      - name: windows Script Current directory
        run: pwd
        shell: bash