name: Shell commands
on: [push]
jobs:
  hello-world:
    runs-on: ubuntu-latest
    steps:
      - name: Hello World
        run: echo "Hello World!"
  get-versions:
    runs-on: ubuntu-latest
    steps:
      - name: 
        run: | 
          node --version
          npm --version