name: Shell commands
on: [push]
jobs:
  run-shell-commands:
    runs-on: ubuntu-latest
    steps:
      - name: eco string
        run: echo "Hello World"
  run-shell-commands:
    runs-on: ubuntu-latest
    steps:
      - name: multiline script
        run: | 
          node --version
          npm --version